[package]
name = "prime_encode"
version = "0.1.0"
authors = ["Naviigator"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
human-sort = "0.2.2"
threadpool = "1.8.1"